// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionRouting.Infrastructure.Persistence;

#nullable disable

namespace ProductionRouting.Infrastructure.Migrations
{
    [DbContext(typeof(ProductionRoutingDbContext))]
    partial class ProductionRoutingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionRouting.Domain.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int");

                    b.Property<int?>("RulesetId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.HasIndex("RulesetId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("ProductionRouting.Domain.Entities.EvaluationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Matched")
                        .HasColumnType("bit");

                    b.Property<string>("MatchedRule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchedRuleset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionPlant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvaluationLogs");
                });

            modelBuilder.Entity("ProductionRouting.Domain.Entities.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProductionPlant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RulesetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("ProductionRouting.Domain.Entities.Ruleset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rulesets");
                });

            modelBuilder.Entity("ProductionRouting.Domain.Entities.Condition", b =>
                {
                    b.HasOne("ProductionRouting.Domain.Entities.Rule", null)
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId");

                    b.HasOne("ProductionRouting.Domain.Entities.Ruleset", null)
                        .WithMany("Conditions")
                        .HasForeignKey("RulesetId");
                });

            modelBuilder.Entity("ProductionRouting.Domain.Entities.Rule", b =>
                {
                    b.HasOne("ProductionRouting.Domain.Entities.Ruleset", null)
                        .WithMany("Rules")
                        .HasForeignKey("RulesetId");
                });

            modelBuilder.Entity("ProductionRouting.Domain.Entities.Rule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("ProductionRouting.Domain.Entities.Ruleset", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
